### PR TITLE
Factor out C-API, Python API and solver tests into their own crates

### PR DESCRIPTION
**Pull request by chrjabs**
Something about dependency resolution makes this break on macos and windows but not on Linux.

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
This is just some uninformed advice, based on hitting a similar issue (you can see people talking about it here: https://github.com/rust-lang/cargo/issues/6313 )

Basically, I think, cdylibs don't work well with packages that get built multiple times, and rustsat is now built with different features in different places.

The best (again, I think) solution would be to pull the C and Python interface out into their own little package, which requires `rustsat`. Nothing depends on that interface package, and that should "break the cycle" (although as I say, I'm guessing here).

You could try removing `cdylib` and see if that at least breaks the set of broken tests, to see if that moves things in the right direction?

**Comment by chrjabs** [comment]
Thanks for the pointers, that might come in very handy. So far I wanted to keep the Python API in the main crate so that it can follow the main versioning more easily, but this might have to change then.

**Comment by chrjabs** [comment]
Looks like the `cdylib` is indeed the problem. I guess I'll have to factor out the external APIs indeed then. At least that seems like the cleanest solution.

**Comment by chrjabs** [comment]
To-dos before merging:
- [ ] Ignore `rustsat-pyapi` in release-plz
- [ ] Factor out solver unit tests into `rustsat-solvertests`

**Pull request merged**
